baseURL: "https://jdjuli.github.io/virto/"
#baseURL: /virto/
languageCode: "en-us"
title: "ViRto"
theme: "paper"
publishDir: "docs"

menu:
  main:
  - identifier: components
    name: Components
    url: /components/
  - identifier: latest
    name: Latest scene
    url: /scenes/demos/demo21


outputs:
    home:
        - HTML
        - RSS

params:
    author: Julian Sanchez Fernandez

