baseURL: "https://jdjuli.github.io/vr-programming/"
#baseURL: "http://localhost:1313/"
languageCode: "en-us"
title: "VR Programming"
theme: "paper"
publishDir: "docs"

outputs:
    home:
        - HTML
        - RSS
        - JSON
params:
    author: Julian Sanchez Fernandez
