baseURL: "https://jdjuli.github.io/vr-programming/"
#baseURL: /vr-programming/
languageCode: "en-us"
title: "VR Programming"
theme: "paper"
publishDir: "docs"

menu:
  main:
  - identifier: components
    name: Components
    url: /components/
  - identifier: latest
    name: Latest scene
    url: /scenes/demos/demo19


outputs:
    home:
        - HTML
        - RSS

params:
    author: Julian Sanchez Fernandez

